# Generated by Django 2.1.7 on 2019-06-02 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190601_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='salary',
        ),
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
