# Generated by Django 2.1.7 on 2019-06-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_register_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_type',
            field=models.TextField(default='', max_length=500),
        ),
    ]
