# Generated by Django 2.1.7 on 2019-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_register_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
